services:
  - type: web
    name: customer-feedback-analytics
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -c "
      import nltk
      nltk.download('punkt', quiet=True)
      nltk.download('stopwords', quiet=True)
      nltk.download('wordnet', quiet=True)
      nltk.download('vader_lexicon', quiet=True)
      "
      python -m spacy download en_core_web_sm
      mkdir -p data/raw data/processed models/sentiment models/topics reports logs
      echo "Generating sample data..."
      python run_pipeline.py
    startCommand: streamlit run app_production.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"