# Customer Feedback Analytics Configuration

# Data Configuration
data:
  raw_data_path: "data/raw/customer_reviews.csv"
  processed_data_path: "data/processed/preprocessed_reviews.csv"
  predictions_path: "data/processed/sentiment_predictions.csv"
  
  # Dataset parameters - INCREASED FROM 10000 TO 16000
  num_reviews: 17000
  categories:
    - Electronics
    - Fashion
    - Home & Kitchen
    - Sports & Outdoors
    - Beauty & Personal Care
    - Books
    - Toys & Games
    - Health & Household
  
  # Data quality simulation
  typo_rate: 0.15
  slang_rate: 0.20
  mixed_expression_rate: 0.10

# Preprocessing Configuration - RELAXED LENGTH CONSTRAINTS
preprocessing:
  min_review_length: 5      # Reduced from 10 to 5
  max_review_length: 1500   # Increased from 1000 to 1500
  remove_stopwords: true
  lemmatize: true
  handle_negations: true
  
  # Text cleaning
  remove_urls: true
  remove_emails: true
  remove_special_chars: true
  lowercase: true

# Model Configuration
models:
  sentiment:
    # Traditional ML
    tfidf:
      max_features: 17000
      ngram_range: [1, 3]
      min_df: 5
      max_df: 0.95
    
    # Deep Learning
    lstm:
      embedding_dim: 100
      hidden_dim: 128
      num_layers: 2
      dropout: 0.3
      learning_rate: 0.001
      batch_size: 32
      epochs: 10
    
    # Transformer
    transformer:
      model_name: "distilbert-base-uncased"
      max_length: 256
      learning_rate: 2e-5
      batch_size: 16
      epochs: 3
  
  topic_modeling:
    num_topics: 12            # Increased from 10 to 12 for more data
    min_topic_size: 50
    n_gram_range: [1, 2]
    diversity: 0.3
    
# Analysis Configuration
analysis:
  confidence_threshold: 0.8
  trend_window_days: 30
  anomaly_detection:
    contamination: 0.05
    algorithm: "isolation_forest"
  
  # Business metrics
  critical_sentiment_threshold: 0.3  # Below this is critical
  satisfaction_goal: 0.8  # 80% positive sentiment target

# Dashboard Configuration
dashboard:
  port: 8501
  theme: "light"
  refresh_interval: 60  # seconds
  
  # Visualization settings
  color_scheme:
    positive: "#2ECC71"
    negative: "#E74C3C"
    neutral: "#95A5A6"
  
  # Chart configurations
  charts:
    show_confidence_scores: true
    show_sample_reviews: true
    max_reviews_display: 100

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/customer_feedback_analytics.log"
  
# Performance Configuration
performance:
  max_workers: 4
  chunk_size: 1000
  cache_enabled: true
  cache_ttl: 3600  # seconds

# Business Rules
business_rules:
  urgent_response_keywords:
    - "urgent"
    - "immediately"
    - "asap"
    - "terrible"
    - "worst"
    - "scam"
    - "fraud"
  
  high_value_categories:
    - Electronics
    - Home & Kitchen
  
  sentiment_weights:
    rating_weight: 0.3
    text_weight: 0.7